controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\DefaultController::index

home:
    path: /home
    controller: App\Controller\DefaultController::index

about:
    path: /apropos
    controller: App\Controller\DefaultController::apropos

contact:
    path: /apropos
    controller: App\Controller\DefaultController::contact


